name: Autoapprove PR
on:
  issue_comment:
    types: [created]
jobs:
  automated-pull-request:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: checkout
        name: Check Out y cambio a rama main
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: get_timestamp
        id: get_timestamp
        run: |
          echo $(date +'%Y%m%d%H%M%S')
          echo "rama=deploy$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      
      - id: create_branch
        name: "[EKS] Create Branch"
        run: |
          git config user.name "action-tests[bot]"
          git config user.email "action-tests[bot]@users.noreply.github.com"
          git checkout -b ${{ steps.get_timestamp.outputs.rama}} main
          git push --set-upstream origin ${{ steps.get_timestamp.outputs.rama }}
          
        #git pull
        #  sudo apt-get install sed
        #  sed -i 's/IMAGEN222.*/IMAGEN333:prueba333/' ./terraform.tfvars
        #  git status
        #  git add -A
        #  git commit -m "Updated file for deploying image: ${{ steps.get_timestamp.outputs.rama }}!!"
        #  git push --set-upstream origin ${{ steps.get_timestamp.outputs.rama }}

     # - id: checkout_for_pr
     #   name: Check Out y cambio a rama main
     #   uses: actions/checkout@v3
     #   with:
     #     ref: ${{ steps.get_timestamp.outputs.rama }}

     # - id: last_deploy
     #   name: Registrar autor del commit
     #   run: echo ${{ steps.get_timestamp.outputs.rama }} > LAST_DEPLOY

      - name: Crear PR
        id: pr_creation
        uses: peter-evans/create-pull-request@v4
        with:
          branch: ${{ steps.get_timestamp.outputs.rama }}
          base: main
          title: "[DEPLOY BY COMMENT] Automatic PR ${{ steps.get_timestamp.outputs.rama }}"
          body:
            Prueba de PR autom√°tica - ${{ steps.get_timestamp.outputs.rama }}
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false
